version: '2'
services:

  app:
    restart: always
    build: app/.
    links:
      - db
    depends_on:
      - db

  db:
    restart: always
    build: db/.
    volumes:
      - /var/lib/mysql:/var/lib/mysql
    environment:
       MYSQL_DATABASE: "factory"
       MYSQL_ROOT_PASSWORD: password

  www:
    restart: always
    build: nginx/.
    links:
      - app
    depends_on:
      - app
    ports:
      - "80:80"
